apiVersion: v1
kind: ConfigMap
metadata:
  name: #{service}#-configmap
  namespace: #{namespace}#
  labels:
    app.bancolombia.com.co/env: #{env}#
    app.bancolombia.com.co/cost-center: #{cost-center}#
    app.bancolombia.com.co/application-code: #{application-code}#
    app.bancolombia.com.co/project: #{project-name}#
    app.bancolombia.com.co/pmo: #{pmo}#
data:
  config.exs: |-
    import Config
    config :fua,
           http_port: 8083,
           enable_server: true,
           secret_name_rds: "#{secret-name-rds}#",
           secret_name: "#{secret-name}#",
           region: "#{secret-region}#",
           token_exp: 3600,
           version: "#{version}#"
    config :ex_aws,
           region: "#{secret-region}#",
           access_key_id: [{:awscli, "profile_name", 30}],
           secret_access_key: [{:awscli, "profile_name", 30}],
           awscli_auth_adapter: ExAws.STS.AuthCache.AssumeRoleWebIdentityAdapter
    config :logger,
           level: #{log-level-ex}#
    config :fua,
           Fua.Adapters.Repositories.Repo,
           database: "#{db-schema}#",
           username: System.get_env("username"),
           password: System.get_env("password"),
           hostname: System.get_env("hostname"),
           pool_size: #{db-pool-size}#