apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: #{service}#-hpa
  namespace: #{namespace}#
spec:
  minReplicas: #{replicas}#
  maxReplicas: #{max-replicas}#
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{service}#-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: #{target-CPU}#